export const homePage = 'HomePage'
export const loginPage = 'LoginPage'
export const logoutPage = 'LogoutPage'

export const securityPage = 'SecurityPage'
export const securityCurrentGroup = 'SecurityCurrentGroup'
export const securityList = 'SecurityList'
export const securityMainReport = 'SecurityMainReport'
export const carsPage = 'CarsPage'
export const visitorsPage = 'VisitorsPage'
export const alarmsPage = 'AlarmsPage'
export const eventsPage = 'EventsPage'
export const cardsPage = 'CardsPage'
export const reportsPage = 'ReportsPage'
export const reportOverviewPage = 'ReportOverviewPage'
export const reportAnaliticsPage = 'ReportAnaliticsPage'
export const devicesPage = 'DevicesPage'

export const adminEditUsersPage = 'AdminEditUsersPage'
