export const homePage = '/'
export const loginPage = '/login'
export const logoutPage = '/logout'

export const securityPage = '/security'
export const securityCurrentGroup = '/security/group'
export const securityList = '/security/list'
export const securityMainReport = '/security/report'
export const carsPage = '/cars'
export const visitorsPage = '/visitors'
export const alarmsPage = '/alarms'
export const eventsPage = '/events'
export const cardsPage = '/cards'
export const reportsPage = '/reports'
export const reportOverviewPage = '/reports/overview'
export const reportAnaliticsPage = '/reports/analitics'
export const devicesPage = '/devices'

export const adminPage = '/admin'
export const adminEditUsersPage = '/admin/edit-users'
export const adminEditCardsPage = '/admin/edit-cards'
